/// Flutter icons Iconspatient
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconspatient
///      fonts:
///       - asset: fonts/Iconspatient.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Iconspatient {
  Iconspatient._();

  static const _kFontFam = 'Iconspatient';
  static const String? _kFontPkg = null;

  static const IconData group_163 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_176 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_346 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_355 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_tooth_dental_dentist_healthcare_medical_medicine = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmlid_345_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anxiety = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby_boy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain_neuron_intelligence_mind = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus = IconData(0xf271, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lungs = IconData(0xf604, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xf77c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
