/// Flutter icons PatientTracker
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PatientTracker
///      fonts:
///       - asset: fonts/PatientTrackericon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PatientTracker {
  PatientTracker._();

  static const _kFontFam = 'PatientTracker';
  static const String? _kFontPkg = null;

  static const IconData group_163 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_176 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_346 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_355 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_tooth_dental_dentist_healthcare_medical_medicine = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmlid_345_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anxiety = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby_boy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain_neuron_intelligence_mind = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
